In [2]:
# from the beginning of the beginning
import pandas as pd
import numpy as np
import sklearn
import seaborn as sns

iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
test_data = iris[['sepal_length', 'sepal_width']]
iris_x = test_data.iloc[0, :]
array_x = np.array([iris_x, [1, 1]]).T

iris_y = test_data.iloc[1, :]
array_y = np.array([iris_y]).T

res = np.linalg.inv(array_x.T.dot(array_x)).dot(array_x.T).dot(array_y) # weighting
a, b = res # y = ax + b
''' np.linalg()
(array([[ 1.1875 ],                 # intercept
        [-1.15625]]),
 array([], dtype=float64),          # SSE value
 2,                                 # 秩
 array([6.3400562 , 0.25236369]))   # singular value calc
'''
np.linalg.lstsq(array_x, array_y, rcond=-1) # equals above

(array([[ 1.1875 ],
        [-1.15625]]),
 array([], dtype=float64),
 2,
 array([6.3400562 , 0.25236369]))

In [30]:
np.linalg.matrix_rank(array_x)
np.linalg.det(array_x)
# array_x.ndim = 2  

1.5999999999999994